// pub mod core {
//     pub mod yang {
//         pub const NOUN: [&str; 20] = [
//             "Sun",
//             "Day",
//             "Point",
//             "Summer",
//             "Fire",
//             "War",
//             "Lyrics",
//             "Father",
//             "Boy",
//             "Cockeral",
//             "Heaven",
//             "God",
//             "Mountain",
//             "Head",
//             "Front",
//             "Lightning",
//             "Eyes",
//             "Soul",
//             "South",
//             "Light",
//         ];
//         pub const VERB: [&str; 26] = [
//             "Winning",
//             "Appearing",
//             "Leading",
//             "Seeing",
//             "Initiating",
//             "Sending",
//             "Arousing",
//             "Energising",
//             "Charging",
//             "Animating",
//             "Conveying",
//             "Directing",
//             "Transmitting",
//             "Relaying",
//             "Consigning",
//             "Multiplying",
//             "Augmenting",
//             "Surging",
//             "Lifting",
//             "Fighting",
//             "Enchanting",
//             "Generating",
//             "Articulating",
//             "Telling",
//             "Starting",
//             "Attacking",
//         ];
//         pub const ADVERB: [&str; 25] = [
//             "Up",
//             "Favorably",
//             "Decisively",
//             "Bravely",
//             "Principally",
//             "Initially",
//             "Fervently",
//             "Vigorously",
//             "Firmly",
//             "Vivaciously",
//             "Immediately",
//             "Exactly",
//             "Bluntly",
//             "Creatively",
//             "Combatively",
//             "Enjoyably",
//             "Agreeably",
//             "Willfully",
//             "Intensely",
//             "Obstinately",
//             "Determinedly",
//             "Persistently",
//             "Inflexibly",
//             "Wildly",
//             "Loudly",
//         ];
//         pub const ADJECTIVE: [&str; 26] = [
//             "White",
//             "Bright",
//             "Warm",
//             "Dry",
//             "Interesting",
//             "Male",
//             "Strong",
//             "Large",
//             "Positive",
//             "Rich",
//             "Long",
//             "Thick",
//             "Good",
//             "Right",
//             "Happy",
//             "Open",
//             "Outside",
//             "Full",
//             "High",
//             "Hard",
//             "Firm",
//             "New",
//             "Arrogant",
//             "Conceited",
//             "Inconsiderate",
//             "Careless",
//         ];
//     }
//     pub mod yin {
//         pub const NOUN: [&str; 20] = [
//             "Moon", "Night", "Surface", "Winter", "Water", "Peace", "Melody", "Mother", "Girl",
//             "Hen", "Earth", "Demon", "Lake", "Tail", "Back", "Thunder", "Ears", "Body", "North",
//             "Shade",
//         ];
//         pub const VERB: [&str; 26] = [
//             "Losing",
//             "Hiding",
//             "Following",
//             "Hearing",
//             "Responding",
//             "Receiveing",
//             "Resolving",
//             "Consummating",
//             "Crowning",
//             "Terminating",
//             "Cancelling",
//             "Concluding",
//             "Completing",
//             "Gaining",
//             "Procuring",
//             "Supporting",
//             "Caring",
//             "Accomodating",
//             "Guarding",
//             "Listening",
//             "Maintaining",
//             "Concentrating",
//             "Catching",
//             "Soothing",
//             "Maturing",
//             "Defending",
//         ];
//         pub const ADVERB: [&str; 25] = [
//             "Down",
//             "unsuccessfully",
//             "Invisibly",
//             "Sensitively",
//             "emotionally",
//             "Sympathetically",
//             "Cordially",
//             "Diligently",
//             "Flexibly",
//             "Reasonably",
//             "Subsequently",
//             "Extensively",
//             "Upliftingly",
//             "Compassionately",
//             "Encouragingly",
//             "Helpfully",
//             "Peacefully",
//             "Amiably",
//             "Complacently",
//             "Gently",
//             "Mildly",
//             "Calmly",
//             "Carefully",
//             "Discreetly",
//             "Quietly",
//         ];
//         pub const ADJECTIVE: [&str; 26] = [
//             "Black",
//             "Dark",
//             "Cold",
//             "Wet",
//             "Boring",
//             "Female",
//             "Weak",
//             "Small",
//             "Negative",
//             "Poor",
//             "Short",
//             "Thin",
//             "Bad",
//             "Left",
//             "Sad",
//             "Close",
//             "Inside",
//             "Empty",
//             "Low",
//             "Soft",
//             "Flexible",
//             "Old",
//             "Kind",
//             "Patient",
//             "Considerate",
//             "Careful",
//         ];
//     }
// }
//
// pub mod bigram {
//     pub mod yang_yang {
//         pub const NOUN: [&str; 23] = [
//             "Heaven",
//             "Sun",
//             "Air",
//             "Creation",
//             "Initiation",
//             "Assertiveness",
//             "Current",
//             "South",
//             "Summer ",
//             "Noon",
//             "Buds",
//             "Blue",
//             "Father",
//             "Determination",
//             "Nose",
//             "Breath",
//             "Politicians",
//             "Administrators",
//             "Living Room",
//             "Airplane",
//             "Power",
//             "Green",
//             "Supernatural",
//         ];
//         pub const VERB: [&str; 20] = [
//             "Activating",
//             "Ascending",
//             "Radiating",
//             "Blowing",
//             "Creating",
//             "Initiating",
//             "Dominating",
//             "Asserting",
//             "Energising",
//             "Controlling",
//             "Boiling",
//             "Expanding",
//             "Smelling",
//             "Breathing",
//             "Running",
//             "Strategising",
//             "Planning",
//             "Flying",
//             "Displaying",
//             "Leading",
//         ];
//         pub const ADVERB: [&str; 13] = [
//             "Very",
//             "Certainly",
//             "Completely",
//             "Justly",
//             "Victoriously",
//             "Powerfully",
//             "Angrily",
//             "Always",
//             "Quickly",
//             "Defiantly",
//             "Dramatically",
//             "Only",
//             "Technically",
//         ];
//         pub const ADJECTIVE: [&str; 11] = [
//             "Your",
//             "Active",
//             "Those",
//             "Internal",
//             "Amazing",
//             "Important",
//             "Arrogant",
//             "Conceited",
//             "condescending",
//             "unkind",
//             "Aloof",
//         ];
//     }
//     pub mod yang_yin {
//         pub const NOUN: [&str; 22] = [
//             "Life",
//             "Time",
//             "Water",
//             "Endurance",
//             "Origin",
//             "Stong",
//             "Determination",
//             "Vibration",
//             "East",
//             "Spring",
//             "Morning",
//             "Seeds",
//             "Black",
//             "Daughter",
//             "Rationality",
//             "Ears",
//             "Blood",
//             "Scientists",
//             "Engineers",
//             "Bathroom",
//             "Ship",
//             "Money",
//         ];
//         pub const VERB: [&str; 17] = [
//             "Declining",
//             "Living",
//             "Raining",
//             "Enduring",
//             "Trying",
//             "Vibrating",
//             "Slipping",
//             "Warming",
//             "Opening",
//             "Listening",
//             "Growing",
//             "Analysing",
//             "Building",
//             "Navigating",
//             "Saving",
//             "Inspiring",
//             "Giving",
//         ];
//         pub const ADVERB: [&str; 12] = [
//             "Quite",
//             "Almost",
//             "Practically",
//             "Bravely",
//             "Vivaciously",
//             "Fortunately",
//             "Anxiously",
//             "Occasionally",
//             "Down",
//             "Slowly",
//             "Awkwardly",
//             "Evenly",
//         ];
//         pub const ADJECTIVE: [&str; 5] = ["Her", "This", "Great", "Interesting", "Attentive"];
//     }
//     pub mod yin_yang {
//         pub const NOUN: [&str; 21] = [
//             "Death",
//             "Space",
//             "Fire",
//             "Consume",
//             "Short",
//             "spontaneity",
//             "Light",
//             "West",
//             "Autumn",
//             "Evening",
//             "Flowers",
//             "White",
//             "Son",
//             "Enthusiasm",
//             "Eyes",
//             "Nerves",
//             "Artists",
//             "Athletes",
//             "Kitchen",
//             "Train",
//             "Beauty",
//         ];
//         pub const VERB: [&str; 17] = [
//             "Rising",
//             "Passing",
//             "Burning",
//             "Consuming",
//             "Brightening",
//             "Rising",
//             "Changing",
//             "Blooming",
//             "Enthusing",
//             "Seeing",
//             "Mating",
//             "Imagining",
//             "Competing",
//             "Moving",
//             "Showing",
//             "Praising",
//             "Taking",
//         ];
//         pub const ADVERB: [&str; 11] = [
//             "Moderately",
//             "Partly",
//             "Cheerfully",
//             "Inncocently",
//             "Eagerly",
//             "Boastfully",
//             "Sometimes",
//             "Up",
//             "Quickly",
//             "Accidentally",
//             "Loosely",
//         ];
//         pub const ADJECTIVE: [&str; 7] = [
//             "His",
//             "That",
//             "Momentary",
//             "Bright",
//             "Good",
//             "Different",
//             "Distracted",
//         ];
//     }
//     pub mod yin_yin {
//         pub const NOUN: [&str; 22] = [
//             "Earth",
//             "Moon",
//             "Soil",
//             "Reception",
//             "Submissive",
//             "Obedience",
//             "Solid",
//             "North",
//             "Winter",
//             "Night",
//             "Branches",
//             "Red",
//             "Mother",
//             "Practicality",
//             "Mouth",
//             "Workers",
//             "Farmers",
//             "Bedroom",
//             "Car",
//             "Health",
//             "Yellow",
//             "Natural",
//         ];
//         pub const VERB: [&str; 22] = [
//             "Existing",
//             "Shining",
//             "Providing",
//             "Receiving",
//             "Absorbing",
//             "Submitting",
//             "Obeying",
//             "Supporting",
//             "Grounding",
//             "Freezing",
//             "Transforming",
//             "Encouraging",
//             "Communicating",
//             "Digesting",
//             "Resting",
//             "Generating",
//             "Growing",
//             "Travelling",
//             "Being",
//             "Loving",
//             "Considering",
//             "Connecting",
//         ];
//         pub const ADVERB: [&str; 14] = [
//             "Mildly",
//             "Sparingly",
//             "Gracefully",
//             "Honestly",
//             "Elegantly",
//             "Safely",
//             "Faithfully",
//             "Wearily",
//             "Finally",
//             "Promptly",
//             "Solemnly",
//             "Mysteriously",
//             "Exactly",
//             "Seriously",
//         ];
//         pub const ADJECTIVE: [&str; 12] = [
//             "Our",
//             "Passive",
//             "These",
//             "Gentle",
//             "External",
//             "Beautiful",
//             "Perfect",
//             "Humble",
//             "Meek",
//             "Considerate",
//             "Kind",
//             "Connected",
//         ];
//     }
// }
//
// pub mod hexagram {
//     pub enum Line {
//         yin,
//         yang,
//     }
//     pub struct Words<'a> {
//         noun: &'a str,
//         verb: &'a str,
//         adjective: &'a str,
//     }
//     pub struct HLine<'a> {
//         correctness: Line,
//         binary: u8,
//         quality: Words<'a>,
//         social_position: Words<'a>,
//     }
//     pub const TOP: HLine = HLine {
//         correctness: Line::yin,
//         binary: 0,
//         quality: Words {
//             noun: "Truth",
//             verb: "Realising",
//             adjective: "Superior",
//         },
//         social_position: Words {
//             noun: "Teacher",
//             verb: "Guiding",
//             adjective: "Sage",
//         },
//     };
//     pub const FIFTH: HLine = HLine {
//         correctness: Line::yang,
//         binary: 1,
//         quality: Words {
//             noun: "Expertise",
//             verb: "Ascending",
//             adjective: "Special",
//         },
//         social_position: Words {
//             noun: "King",
//             verb: "Ruling",
//             adjective: "Regal",
//         },
//     };
//     pub const FOURTH: HLine = HLine {
//         correctness: Line::yin,
//         binary: 0,
//         quality: Words {
//             noun: "Risk",
//             verb: "Readying",
//             adjective: "Precarious",
//         },
//         social_position: Words {
//             noun: "Minister",
//             verb: "Instructing",
//             adjective: "Judicial",
//         },
//     };
//     pub const THIRD: HLine = HLine {
//         correctness: Line::yang,
//         binary: 1,
//         quality: Words {
//             noun: "Vocation",
//             verb: "Waiting",
//             adjective: "Insecure",
//         },
//         social_position: Words {
//             noun: "Lord",
//             verb: "Leading",
//             adjective: "Distinguished",
//         },
//     };
//     pub const SECOND: HLine = HLine {
//         correctness: Line::yin,
//         binary: 0,
//         quality: Words {
//             noun: "Education",
//             verb: "Learning",
//             adjective: "Sheltered",
//         },
//         social_position: Words {
//             noun: "Official",
//             verb: "Helping",
//             adjective: "Administrative",
//         },
//     };
//     pub const INITIAL: HLine = HLine {
//         correctness: Line::yang,
//         binary: 1,
//         quality: Words {
//             noun: "Transition",
//             verb: "Transforming",
//             adjective: "Transient",
//         },
//         social_position: Words {
//             noun: "Folk",
//             verb: "Following",
//             adjective: "Ordinary",
//         },
//     };
// }
//
// pub mod trigram {
//     pub enum Line {
//         central,
//         top,
//         bottom,
//     }
//     pub struct TLine<'a> {
//         image: &'a str,
//         binary: &'a str,
//         no: u8,
//         wen: u8,
//         host: Line,
//         element: &'a str,
//         inner_splitting: &'a str,
//         outer_splitting: &'a str,
//         interpretation: &'a str,
//         nuons: &'a str,
//         verbs: &'a str,
//         adjectives: &'a str,
//         adverbs: &'a str,
//         life: &'a str,
//         direction: &'a str,
//         season: &'a str,
//         time: &'a str,
//         planet: &'a str,
//         colour: &'a str,
//         family: &'a str,
//         body: &'a str,
//         organ: &'a str,
//         animal: &'a str,
//         inversion: u8,
//         reversion: u8,
//     }
//     pub const HEAVEN: TLine = TLine {
//         image: "☰",
//         binary: "111",
//         no: 19,
//         wen: 1,
//         host: Line::central,
//         element: "Fire",
//         inner_splitting: "Air that goes high",
//         outer_splitting: "What lifts air high",
//         interpretation: "Firmness",
//         nuons: "expression, passion, warmth, love, initiation, leadership, egocentricity, clarity, awareness, arrogance, clear",
//         verbs: "initiating, dominating, activating, strengthening, warming, loving, leading, pushing, emboldening, clarifying, enlightening, stimulating",
//         adjectives: "creative, clarity, conscious, mindful, purposeful",
//         adverbs: "angrily, boldly",
//         life: "adulthood",
//         direction: "north west",
//         season: "summer",
//         time: "noon",
//         planet: "Uranus",
//         colour: "blue",
//         family: "father",
//         body: "head",
//         organ: "mouth",
//         animal: "horse",
//         inversion: 8,
//         reversion: 1,
//     };
//     pub const LAKE: TLine = TLine {
//         image: "☱",
//         binary: "110",
//         no: 2,
//         wen: 8,
//         host: Line::bottom,
//         element: "Metal",
//         inner_splitting: "Water that goes high",
//         outer_splitting: "What pushes air low",
//         interpretation: "Soft in appearance",
//         nuons: "humility, connection, inspiration, enjoyment, delight, melancholia, benefit, fullfillment, inspiration",
//         verbs: "benefiting, delighting, enjoying, pleasing, seeing, agreeing, connecting, inspiring, fulfilling",
//         adjectives: "content, open, humble, inspired, joyful, melancholic, beneficial",
//         adverbs: "jealously, bravely",
//         life: "infancy",
//         direction: "west",
//         season: "summer",
//         time: "9am",
//         planet: "Neptune",
//         colour: "cyan",
//         family: "last girl",
//         body: "chest",
//         organ: "gall bladder",
//         animal: "sheep",
//         inversion: 7,
//         reversion: 5,
//     };
//     pub const FIRE: TLine = TLine {
//         image: "☲",
//         binary: "101",
//         no: 3,
//         wen: 7,
//         host: Line::central,
//         element: "Fire",
//         inner_splitting: "Fire that goes high",
//         outer_splitting: "What lifts water high",
//         interpretation: "Soft in contact",
//         nuons: "discernment, attachment, warmth",
//         verbs: "discerning, clinging, grapsing, consuming ---  illuminating, radiating, shining, enlightening, tranforming, determining",
//         adjectives: "hot, bright, luminous, adherent, intelligent, glorious",
//         adverbs: "Irritably, devotedly",
//         life: "enlighten",
//         direction: "south",
//         season: "autunm",
//         time: "6pm",
//         planet: "Mars",
//         colour: "white",
//         family: "2nd girl",
//         body: "nerve",
//         organ: "heart",
//         animal: "pheasant",
//         inversion: 6,
//         reversion: 3,
//     };
//     pub const THUNDER: TLine = TLine {
//         image: "☳",
//         binary: "100",
//         no: 4,
//         wen: 3,
//         host: Line::top,
//         element: "Wood",
//         inner_splitting: "Soil that goes high",
//         outer_splitting: "What pushes water low",
//         interpretation: "firm in core",
//         nuons: "move, agitate, enliven, break, inflame",
//         verbs: "deciding, awakening, breaking, initiating, approaching, arousing, rising, moving",
//         adjectives: "exciting, strong, decisive, movement, flexible, promising",
//         adverbs: "flexibiy, boastfully",
//         life: "embryo",
//         direction: "north east",
//         season: "spring",
//         time: "3am",
//         planet: "Saturn",
//         colour: "red",
//         family: "1st boy",
//         body: "feet",
//         organ: "liver",
//         animal: "dragon",
//         inversion: 5,
//         reversion: 7,
//     };
//     pub const WIND: TLine = TLine {
//         image: "☴",
//         binary: "011",
//         no: 5,
//         wen: 3,
//         host: Line::top,
//         element: "Wood",
//         inner_splitting: "Air that goes low",
//         outer_splitting: "What lift fire high",
//         interpretation: "soft in core",
//         nuons: "promotion, persuasion, dispersion, infiltration, penetration",
//         verbs:
//             "thinking, planning, acting, penetrating, persuading, dispersing, lying, infiltrating",
//         adjectives: "easily, well-rooted, flexible, penetrate, infiltrate",
//         adverbs: "anxiously, justly",
//         life: "decay",
//         direction: "south east",
//         season: "autunm",
//         time: "3pm",
//         planet: "Jupiter",
//         colour: "green",
//         family: "1st girl",
//         body: "butt",
//         organ: "lung",
//         animal: "cockeral",
//         inversion: 4,
//         reversion: 2,
//     };
//     pub const WATER: TLine = TLine {
//         image: "☵",
//         binary: "010",
//         no: 6,
//         wen: 4,
//         host: Line::central,
//         element: "Water",
//         inner_splitting: "Water that goes low",
//         outer_splitting: "What pulls fire low",
//         interpretation: "firm in contact",
//         nuons: "trust, intuition, engagement, anxiety",
//         verbs: "sinking, involving, venturing, engaging, deepening",
//         adjectives: "abysmal, dangerous, shameful, exposed",
//         adverbs: "foolishly, gleefully",
//         life: "pregnancy",
//         direction: "north",
//         season: "spring",
//         time: "6am",
//         planet: "Mercury",
//         colour: "black",
//         family: "2nd boy",
//         body: "blood",
//         organ: "kidney",
//         animal: "pig",
//         inversion: 3,
//         reversion: 6,
//     };
//     pub const MOUNTAIN: TLine = TLine {
//         image: "☶",
//         binary: "001",
//         no: 7,
//         wen: 5,
//         host: Line::bottom,
//         element: "Metal",
//         inner_splitting: "Fire that goes low",
//         outer_splitting: "What lifts soil high",
//         interpretation: "firm in appearance",
//         nuons: "disengagement, recognition, grief, stillness, faithfulness, memorable, repose, cumulate",
//         verbs: "persevering, waiting, meditating, stoping, standing, accumulating, accomplishing, resting, grieving, hatling, acknowledging",
//         adjectives: "memorably, slowly, faithfully, meditatively, ",
//         adverbs: "restfully, patiently, slowly, patiently",
//         life: "end",
//         direction: "east",
//         season: "winter",
//         time: "9pm",
//         planet: "Pluto",
//         colour: "yellow",
//         family: "last boy",
//         body: "abdomen",
//         organ: "stomach",
//         animal: "dog",
//         inversion: 2,
//         reversion: 4,
//     };
//     pub const EARTH: TLine = TLine {
//         image: "☷",
//         binary: "000",
//         no: 80,
//         wen: 2,
//         host: Line::central,
//         element: "Earth",
//         inner_splitting: "Soil that goes low",
//         outer_splitting: "What pulls soil low",
//         interpretation: "softness",
//         nuons: "stability, compassion, commitment, peace, multiplication, propagation, nurture, docile, calm",
//         verbs: "responding, receiving, quietening, yielding, nurturing, propegating, stabalising, calming, allowing",
//         adjectives: "receptive, dark, soft, flexible, adaptive, fertile, peacful, gentle",
//         adverbs: "lazily, perfectly, slowly",
//         life: "reception",
//         direction: "south wast",
//         season: "winter",
//         time: "midnight",
//         planet: "Venus",
//         colour: "brown",
//         family: "mother",
//         body: "back",
//         organ: "teeth",
//         animal: "cow",
//         inversion: 1,
//         reversion: 8,
//     };
// }
